# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CruiseGui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(474, 254)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelHenryHack = QtWidgets.QLabel(self.centralwidget)
        self.labelHenryHack.setGeometry(QtCore.QRect(10, 10, 101, 16))
        self.labelHenryHack.setObjectName("labelHenryHack")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(150, 90, 82, 75))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnCruiseUp = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCruiseUp.setObjectName("btnCruiseUp")
        self.verticalLayout.addWidget(self.btnCruiseUp)
        self.labelCruise = QtWidgets.QLabel(self.layoutWidget)
        self.labelCruise.setObjectName("labelCruise")
        self.verticalLayout.addWidget(self.labelCruise)
        self.btnCruiseDown = QtWidgets.QPushButton(self.layoutWidget)
        self.btnCruiseDown.setObjectName("btnCruiseDown")
        self.verticalLayout.addWidget(self.btnCruiseDown)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 90, 82, 75))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btnVolUp = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnVolUp.setObjectName("btnVolUp")
        self.verticalLayout_2.addWidget(self.btnVolUp)
        self.labelMusicVol = QtWidgets.QLabel(self.layoutWidget1)
        self.labelMusicVol.setObjectName("labelMusicVol")
        self.verticalLayout_2.addWidget(self.labelMusicVol)
        self.btnVolDown = QtWidgets.QPushButton(self.layoutWidget1)
        self.btnVolDown.setObjectName("btnVolDown")
        self.verticalLayout_2.addWidget(self.btnVolDown)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 30, 298, 25))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelStartCan = QtWidgets.QLabel(self.layoutWidget2)
        self.labelStartCan.setObjectName("labelStartCan")
        self.horizontalLayout.addWidget(self.labelStartCan)
        self.btnOpenCan = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnOpenCan.setObjectName("btnOpenCan")
        self.horizontalLayout.addWidget(self.btnOpenCan)
        self.btnCloseCan = QtWidgets.QPushButton(self.layoutWidget2)
        self.btnCloseCan.setObjectName("btnCloseCan")
        self.horizontalLayout.addWidget(self.btnCloseCan)
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.labelHenryHack.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 474, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelHenryHack.setText(_translate("MainWindow", "Aalto Henry Hack"))
        self.btnCruiseUp.setText(_translate("MainWindow", "Speed up"))
        self.labelCruise.setText(_translate("MainWindow", "Cruise Control:"))
        self.btnCruiseDown.setText(_translate("MainWindow", "Speed down"))
        self.btnVolUp.setText(_translate("MainWindow", "Vol up"))
        self.labelMusicVol.setText(_translate("MainWindow", "Music Volume:"))
        self.btnVolDown.setText(_translate("MainWindow", "Vol down"))
        self.labelStartCan.setText(_translate("MainWindow", "Start Can with 500 kbaud"))
        self.btnOpenCan.setText(_translate("MainWindow", "Open"))
        self.btnCloseCan.setText(_translate("MainWindow", "Close"))

